//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojohive {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class DataSourceFactory : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_instance0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDataSource1;
        
        protected DataSourceFactory(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::mojohive.DataSourceFactory.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::mojohive.DataSourceFactory.staticClass = @__class;
            global::mojohive.DataSourceFactory.j4n_instance0 = @__env.GetStaticMethodID(global::mojohive.DataSourceFactory.staticClass, "instance", "()Lmojohive/DataSourceFactory;");
            global::mojohive.DataSourceFactory.j4n_getDataSource1 = @__env.GetMethodID(global::mojohive.DataSourceFactory.staticClass, "getDataSource", "(Lmojohive/ConnectionParams;)Ljavax/sql/DataSource;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lmojohive/DataSourceFactory;")]
        public static global::mojohive.DataSourceFactory instance() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::mojohive.DataSourceFactory>(@__env, @__env.CallStaticObjectMethodPtr(global::mojohive.DataSourceFactory.staticClass, global::mojohive.DataSourceFactory.j4n_instance0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lmojohive/ConnectionParams;)Ljavax/sql/DataSource;")]
        public virtual global::java.lang.Object getDataSource(global::mojohive.ConnectionParams par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.DataSourceFactory.j4n_getDataSource1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::mojohive.DataSourceFactory(@__env);
            }
        }
    }
    #endregion
}
