//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojohive {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface IMojoHiveDriver {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
            "ng/String;)I")]
        int TestConnection(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/String;")]
        global::java.lang.String TestNamedPipeRead(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)I")]
        int TestNamedPipeWrite(global::java.lang.String par0, global::java.lang.String par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
            "ng/String;Ljava/lang/String;)Ljava/lang/String;")]
        global::java.lang.String QueryResultSetAsXML(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4, global::java.lang.String par5);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
            "ng/String;Ljava/lang/String;Ljava/lang/String;)I")]
        int QueryResultSetToPipe(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4, global::java.lang.String par5, global::java.lang.String par6);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        global::java.lang.String GetLastExceptionMessage();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        global::java.lang.String GetLastExceptionStackTrace();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        int GetLastErrorCode();
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class IMojoHiveDriver_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::mojohive.@__IMojoHiveDriver.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::mojohive.IMojoHiveDriver), typeof(global::mojohive.IMojoHiveDriver_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::mojohive.IMojoHiveDriver), typeof(global::mojohive.IMojoHiveDriver_))]
    internal sealed partial class @__IMojoHiveDriver : global::java.lang.Object, global::mojohive.IMojoHiveDriver {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_TestConnection0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_TestNamedPipeRead1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_TestNamedPipeWrite2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_QueryResultSetAsXML3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_QueryResultSetToPipe4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetLastExceptionMessage5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetLastExceptionStackTrace6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetLastErrorCode7;
        
        private @__IMojoHiveDriver(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::mojohive.@__IMojoHiveDriver.staticClass = @__class;
            global::mojohive.@__IMojoHiveDriver.j4n_TestConnection0 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "TestConnection", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                    "ng/String;)I");
            global::mojohive.@__IMojoHiveDriver.j4n_TestNamedPipeRead1 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "TestNamedPipeRead", "(Ljava/lang/String;)Ljava/lang/String;");
            global::mojohive.@__IMojoHiveDriver.j4n_TestNamedPipeWrite2 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "TestNamedPipeWrite", "(Ljava/lang/String;Ljava/lang/String;)I");
            global::mojohive.@__IMojoHiveDriver.j4n_QueryResultSetAsXML3 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "QueryResultSetAsXML", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                    "ng/String;Ljava/lang/String;)Ljava/lang/String;");
            global::mojohive.@__IMojoHiveDriver.j4n_QueryResultSetToPipe4 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "QueryResultSetToPipe", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                    "ng/String;Ljava/lang/String;Ljava/lang/String;)I");
            global::mojohive.@__IMojoHiveDriver.j4n_GetLastExceptionMessage5 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "GetLastExceptionMessage", "()Ljava/lang/String;");
            global::mojohive.@__IMojoHiveDriver.j4n_GetLastExceptionStackTrace6 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "GetLastExceptionStackTrace", "()Ljava/lang/String;");
            global::mojohive.@__IMojoHiveDriver.j4n_GetLastErrorCode7 = @__env.GetMethodID(global::mojohive.@__IMojoHiveDriver.staticClass, "GetLastErrorCode", "()I");
        }
        
        public int TestConnection(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 20)){
            return ((int)(@__env.CallIntMethod(this, global::mojohive.@__IMojoHiveDriver.j4n_TestConnection0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par3), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par4))));
            }
        }
        
        public global::java.lang.String TestNamedPipeRead(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.@__IMojoHiveDriver.j4n_TestNamedPipeRead1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public int TestNamedPipeWrite(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((int)(@__env.CallIntMethod(this, global::mojohive.@__IMojoHiveDriver.j4n_TestNamedPipeWrite2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1))));
            }
        }
        
        public global::java.lang.String QueryResultSetAsXML(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4, global::java.lang.String par5) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 22)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.@__IMojoHiveDriver.j4n_QueryResultSetAsXML3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par3), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par4), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par5)));
            }
        }
        
        public int QueryResultSetToPipe(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4, global::java.lang.String par5, global::java.lang.String par6) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 24)){
            return ((int)(@__env.CallIntMethod(this, global::mojohive.@__IMojoHiveDriver.j4n_QueryResultSetToPipe4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par3), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par4), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par5), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par6))));
            }
        }
        
        public global::java.lang.String GetLastExceptionMessage() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.@__IMojoHiveDriver.j4n_GetLastExceptionMessage5));
            }
        }
        
        public global::java.lang.String GetLastExceptionStackTrace() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.@__IMojoHiveDriver.j4n_GetLastExceptionStackTrace6));
            }
        }
        
        public int GetLastErrorCode() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::mojohive.@__IMojoHiveDriver.j4n_GetLastErrorCode7)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__IMojoHiveDriver);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "TestConnection", "TestConnection0", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                        "ng/String;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "TestNamedPipeRead", "TestNamedPipeRead1", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "TestNamedPipeWrite", "TestNamedPipeWrite2", "(Ljava/lang/String;Ljava/lang/String;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "QueryResultSetAsXML", "QueryResultSetAsXML3", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                        "ng/String;Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "QueryResultSetToPipe", "QueryResultSetToPipe4", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                        "ng/String;Ljava/lang/String;Ljava/lang/String;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetLastExceptionMessage", "GetLastExceptionMessage5", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetLastExceptionStackTrace", "GetLastExceptionStackTrace6", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetLastErrorCode", "GetLastErrorCode7", "()I"));
            return methods;
        }
        
        private static int TestConnection0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1, global::net.sf.jni4net.utils.JniLocalHandle par2, global::net.sf.jni4net.utils.JniLocalHandle par3, global::net.sf.jni4net.utils.JniLocalHandle par4) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = ((int)(@__real.TestConnection(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par2), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par3), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par4))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle TestNamedPipeRead1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (Ljava/lang/String;)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.TestNamedPipeRead(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int TestNamedPipeWrite2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Ljava/lang/String;Ljava/lang/String;)I
            // (Ljava/lang/String;Ljava/lang/String;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = ((int)(@__real.TestNamedPipeWrite(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle QueryResultSetAsXML3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1, global::net.sf.jni4net.utils.JniLocalHandle par2, global::net.sf.jni4net.utils.JniLocalHandle par3, global::net.sf.jni4net.utils.JniLocalHandle par4, global::net.sf.jni4net.utils.JniLocalHandle par5) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.QueryResultSetAsXML(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par2), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par3), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par4), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par5)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int QueryResultSetToPipe4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1, global::net.sf.jni4net.utils.JniLocalHandle par2, global::net.sf.jni4net.utils.JniLocalHandle par3, global::net.sf.jni4net.utils.JniLocalHandle par4, global::net.sf.jni4net.utils.JniLocalHandle par5, global::net.sf.jni4net.utils.JniLocalHandle par6) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = ((int)(@__real.QueryResultSetToPipe(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par2), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par3), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par4), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par5), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par6))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetLastExceptionMessage5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.GetLastExceptionMessage());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetLastExceptionStackTrace6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.GetLastExceptionStackTrace());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int GetLastErrorCode7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::mojohive.IMojoHiveDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojohive.IMojoHiveDriver>(@__env, @__obj);
            @__return = ((int)(@__real.GetLastErrorCode()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::mojohive.@__IMojoHiveDriver(@__env);
            }
        }
    }
    #endregion
}
