//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojohive {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class ModuleConfiguration : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_instance0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTestJdbcDriverClass1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTestJdbcConnectionUrl2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTestJdbcPassword3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTestJdbcUsername4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTestDbQuery5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isTestMode6;
        
        protected ModuleConfiguration(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::mojohive.ModuleConfiguration.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::mojohive.ModuleConfiguration.staticClass = @__class;
            global::mojohive.ModuleConfiguration.j4n_instance0 = @__env.GetStaticMethodID(global::mojohive.ModuleConfiguration.staticClass, "instance", "()Lmojohive/ModuleConfiguration;");
            global::mojohive.ModuleConfiguration.j4n_getTestJdbcDriverClass1 = @__env.GetMethodID(global::mojohive.ModuleConfiguration.staticClass, "getTestJdbcDriverClass", "()Ljava/lang/String;");
            global::mojohive.ModuleConfiguration.j4n_getTestJdbcConnectionUrl2 = @__env.GetMethodID(global::mojohive.ModuleConfiguration.staticClass, "getTestJdbcConnectionUrl", "()Ljava/lang/String;");
            global::mojohive.ModuleConfiguration.j4n_getTestJdbcPassword3 = @__env.GetMethodID(global::mojohive.ModuleConfiguration.staticClass, "getTestJdbcPassword", "()Ljava/lang/String;");
            global::mojohive.ModuleConfiguration.j4n_getTestJdbcUsername4 = @__env.GetMethodID(global::mojohive.ModuleConfiguration.staticClass, "getTestJdbcUsername", "()Ljava/lang/String;");
            global::mojohive.ModuleConfiguration.j4n_getTestDbQuery5 = @__env.GetMethodID(global::mojohive.ModuleConfiguration.staticClass, "getTestDbQuery", "()Ljava/lang/String;");
            global::mojohive.ModuleConfiguration.j4n_isTestMode6 = @__env.GetMethodID(global::mojohive.ModuleConfiguration.staticClass, "isTestMode", "()Z");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lmojohive/ModuleConfiguration;")]
        public static global::mojohive.ModuleConfiguration instance() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::mojohive.ModuleConfiguration>(@__env, @__env.CallStaticObjectMethodPtr(global::mojohive.ModuleConfiguration.staticClass, global::mojohive.ModuleConfiguration.j4n_instance0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getTestJdbcDriverClass() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.ModuleConfiguration.j4n_getTestJdbcDriverClass1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getTestJdbcConnectionUrl() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.ModuleConfiguration.j4n_getTestJdbcConnectionUrl2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getTestJdbcPassword() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.ModuleConfiguration.j4n_getTestJdbcPassword3));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getTestJdbcUsername() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.ModuleConfiguration.j4n_getTestJdbcUsername4));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getTestDbQuery() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojohive.ModuleConfiguration.j4n_getTestDbQuery5));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isTestMode() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::mojohive.ModuleConfiguration.j4n_isTestMode6)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::mojohive.ModuleConfiguration(@__env);
            }
        }
    }
    #endregion
}
