//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojomysql {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface ISimpleMySQLDriver {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        void RunStaticQuery(global::java.lang.String par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
            "ng/String;)Ljava/lang/String;")]
        global::java.lang.String QueryResultSetAsString(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class ISimpleMySQLDriver_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::mojomysql.@__ISimpleMySQLDriver.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::mojomysql.ISimpleMySQLDriver), typeof(global::mojomysql.ISimpleMySQLDriver_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::mojomysql.ISimpleMySQLDriver), typeof(global::mojomysql.ISimpleMySQLDriver_))]
    internal sealed partial class @__ISimpleMySQLDriver : global::java.lang.Object, global::mojomysql.ISimpleMySQLDriver {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_RunStaticQuery0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_QueryResultSetAsString1;
        
        private @__ISimpleMySQLDriver(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::mojomysql.@__ISimpleMySQLDriver.staticClass = @__class;
            global::mojomysql.@__ISimpleMySQLDriver.j4n_RunStaticQuery0 = @__env.GetMethodID(global::mojomysql.@__ISimpleMySQLDriver.staticClass, "RunStaticQuery", "(Ljava/lang/String;)V");
            global::mojomysql.@__ISimpleMySQLDriver.j4n_QueryResultSetAsString1 = @__env.GetMethodID(global::mojomysql.@__ISimpleMySQLDriver.staticClass, "QueryResultSetAsString", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                    "ng/String;)Ljava/lang/String;");
        }
        
        public void RunStaticQuery(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::mojomysql.@__ISimpleMySQLDriver.j4n_RunStaticQuery0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        public global::java.lang.String QueryResultSetAsString(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 20)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojomysql.@__ISimpleMySQLDriver.j4n_QueryResultSetAsString1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par3), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par4)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ISimpleMySQLDriver);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RunStaticQuery", "RunStaticQuery0", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "QueryResultSetAsString", "QueryResultSetAsString1", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                        "ng/String;)Ljava/lang/String;"));
            return methods;
        }
        
        private static void RunStaticQuery0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljava/lang/String;)V
            // (Ljava/lang/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::mojomysql.ISimpleMySQLDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojomysql.ISimpleMySQLDriver>(@__env, @__obj);
            @__real.RunStaticQuery(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle QueryResultSetAsString1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1, global::net.sf.jni4net.utils.JniLocalHandle par2, global::net.sf.jni4net.utils.JniLocalHandle par3, global::net.sf.jni4net.utils.JniLocalHandle par4) {
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
            // (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::mojomysql.ISimpleMySQLDriver @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::mojomysql.ISimpleMySQLDriver>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.QueryResultSetAsString(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par1), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par2), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par3), global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par4)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::mojomysql.@__ISimpleMySQLDriver(@__env);
            }
        }
    }
    #endregion
}
