//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojomysql {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SimpleMySQLDriver : global::java.lang.Object, global::mojomysql.ISimpleMySQLDriver {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_RunStaticQuery0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_QueryResultSetAsString1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_ConvertResultSetToXML2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSimpleMySQLDriver3;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public SimpleMySQLDriver() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::mojomysql.SimpleMySQLDriver.staticClass, global::mojomysql.SimpleMySQLDriver.j4n__ctorSimpleMySQLDriver3, this);
            }
        }
        
        protected SimpleMySQLDriver(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::mojomysql.SimpleMySQLDriver.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::mojomysql.SimpleMySQLDriver.staticClass = @__class;
            global::mojomysql.SimpleMySQLDriver.j4n_RunStaticQuery0 = @__env.GetMethodID(global::mojomysql.SimpleMySQLDriver.staticClass, "RunStaticQuery", "(Ljava/lang/String;)V");
            global::mojomysql.SimpleMySQLDriver.j4n_QueryResultSetAsString1 = @__env.GetMethodID(global::mojomysql.SimpleMySQLDriver.staticClass, "QueryResultSetAsString", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
                    "ng/String;)Ljava/lang/String;");
            global::mojomysql.SimpleMySQLDriver.j4n_ConvertResultSetToXML2 = @__env.GetMethodID(global::mojomysql.SimpleMySQLDriver.staticClass, "ConvertResultSetToXML", "(Ljava/sql/ResultSet;)Ljava/lang/String;");
            global::mojomysql.SimpleMySQLDriver.j4n__ctorSimpleMySQLDriver3 = @__env.GetMethodID(global::mojomysql.SimpleMySQLDriver.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public virtual void RunStaticQuery(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::mojomysql.SimpleMySQLDriver.j4n_RunStaticQuery0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/la" +
            "ng/String;)Ljava/lang/String;")]
        public virtual global::java.lang.String QueryResultSetAsString(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::java.lang.String par3, global::java.lang.String par4) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 20)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojomysql.SimpleMySQLDriver.j4n_QueryResultSetAsString1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par3), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par4)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/sql/ResultSet;)Ljava/lang/String;")]
        public virtual global::java.lang.String ConvertResultSetToXML(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::mojomysql.SimpleMySQLDriver.j4n_ConvertResultSetToXML2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::mojomysql.SimpleMySQLDriver(@__env);
            }
        }
    }
    #endregion
}
