// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package mojomysql;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class ISimpleMySQLDriver_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return mojomysql.ISimpleMySQLDriver_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        mojomysql.ISimpleMySQLDriver_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __ISimpleMySQLDriver extends system.Object implements mojomysql.ISimpleMySQLDriver {
    
    protected __ISimpleMySQLDriver(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    public native void RunStaticQuery(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
    public native java.lang.String QueryResultSetAsString(java.lang.String par0, java.lang.String par1, java.lang.String par2, java.lang.String par3, java.lang.String par4);
}
//</generated-proxy>
