// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package mojohive;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IMojoHiveDriver_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return mojohive.IMojoHiveDriver_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        mojohive.IMojoHiveDriver_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IMojoHiveDriver extends system.Object implements mojohive.IMojoHiveDriver {
    
    protected __IMojoHiveDriver(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I")
    public native int TestConnection(java.lang.String par0, java.lang.String par1, java.lang.String par2, java.lang.String par3, java.lang.String par4);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/String;")
    public native java.lang.String TestNamedPipeRead(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;)I")
    public native int TestNamedPipeWrite(java.lang.String par0, java.lang.String par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
    public native java.lang.String QueryResultSetAsXML(java.lang.String par0, java.lang.String par1, java.lang.String par2, java.lang.String par3, java.lang.String par4, java.lang.String par5);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I")
    public native int QueryResultSetToPipe(java.lang.String par0, java.lang.String par1, java.lang.String par2, java.lang.String par3, java.lang.String par4, java.lang.String par5, java.lang.String par6);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String GetLastExceptionMessage();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String GetLastExceptionStackTrace();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int GetLastErrorCode();
}
//</generated-proxy>
